baseURL = "http://gliush.github.io/"
languageCode = "en-us"
title = "Gliush Notebook"
theme = "ezhil"
defaultContentLanguage = "en"

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Your Google analytics code.
#googleAnalytics = "UA-123-45"
# Your Disqus sortname.
#disqusShortname = "localhost"

# Number of posts to show in recent posts list (Optional). Defaults to 10.
paginate = 10


[params]
author = "Ivan Glushkov"
# Blog subtitle which appears below blog title. Supports markdown.
subtitle = "Notes about IT, work, and life"
mainSections = ["devzen_note"]
mode = "auto"

[[menu.main]]
identifier = "home"
name = "Home"
title = "Home"
url = "/"
weight = 1

[[menu.main]]
url = "/tags/"
name = "Tags"
title = "Tags"
weight = 2

[[menu.main]]
url = "/categories/"
name = "Categories"
title = "Categories"
weight = 3

[taxonomies]
category = "categories"
tag = "tags"
series = "series"


